### ISSUE TITLE
playlistName

### ISSUE THREAD

**Issue by mp1pro** [tstere/jammming#2]
The reason why the playlistName does not reset when the 'save to spotify' button is clicked is because the value of the input that displays the name has a `defaultValue` instead of `value`

`<input defaultValue={this.props.name} onChange={this.handleNameChange} />`

It should be like this instead;

`<input value={this.props.playlistName} onChange={this.handleNameChange}/>`

in playList.js

**Comment by tstere** [comment]
corrected state
